#!/bin/sh

logger -s -t init $0 $1

# Check needed for UMS vstatmux mode
/bin/whatami --mode UMS && exit

#Java use default locale for work with String
if [ -r "/opt/omneon/config/locale.conf" ]; then
        . /opt/omneon/config/locale.conf
        export LANG
fi

bootp_flag=""
bootp_disable_file="/tmp/.bootp_disable"
bootp_config_file="/opt/omneon/config/network/bootp_interface"

case "$1" in
  start)
        echo "Initializing modules"
        rmmod bonding 2> /dev/null > /dev/null
        modprobe team
        modprobe bridge

        echo "Killing ifplugd and dhclient"
        killall -9 ifplugd 2> /dev/null > /dev/null
        killall -9 dhclient 2> /dev/null > /dev/null
        rm -f /var/run/dhclient.net*.pid 2> /dev/null > /dev/null

        echo "Flushing routing tables"
        ip route flush table eth0-table
        ip route flush table eth1-table
        ip route flush table eth2-table
        ip route flush table eth3-table
        ip route flush table eth4-table
        ip route flush table eth5-table
        ip route flush table eth6-table
        ip route flush table eth7-table

        ip route flush table bond0-table
        ip route flush table bond1-table
        ip route flush table bond2-table
        ip route flush table bond3-table

        ip route flush table subnet-table

        # enable BOOT only on the first start, when system boots
        if [ ! -e "$bootp_disable_file" ]; then
            if [ -e "$bootp_config_file" -a -s "$bootp_config_file" ]; then
                bootp_flag="--bootp"
                touch "$bootp_disable_file"
            fi
        fi

        # Start daemon.
        echo "Starting nminet service daemon"

        cd /opt/omneon/nmi
        start-stop-daemon --start --background --make-pidfile --pidfile /var/run/nminet.pid --startas /opt/omneon/nmi/nminet/bin/nminet -- -v -s $bootp_flag
        ;;
  stop)
        # Stop daemon.
        echo "Shutting down nminet service daemon"
        start-stop-daemon --stop --quiet --signal TERM --oknodo --pidfile /var/run/nminet.pid
        sleep 1
        start-stop-daemon --stop --quiet --signal KILL --oknodo --pidfile /var/run/nminet.pid
        rm -f /var/run/nminet.pid
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac
