#!/bin/sh

logger -s -t init $0 $1

# Check needed for UMS vstatmux mode
/bin/whatami --mode UMS && exit

#Java use default locale for work with String
if [ -r "/opt/omneon/config/locale.conf" ]; then
        . /opt/omneon/config/locale.conf
        export LANG
fi


revert_to_primary_later() {
    bash -c 'sleep 20; /opt/omneon/bin/nminetctl redundancy -r' &> /dev/null < /dev/null &
}

case "$1" in
  start)
        revert_to_primary_later
        ;;
  stop)
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac
